version: "3.4"
services:

  web:
    image: cas-web
    environment:
      - API_URL=${API_URL}
      - USE_SELF_SIGNED_SSL=${USE_SELF_SIGNED_SSL}
      - IpFilterRules=${IpFilterRules}
      - RealIpFrom=${RealIpFrom}
      - WEB_BASE_HREF=${WEB_BASE_HREF}
    ports:
      - 8080:8080
    depends_on:
      - api

  api:
    image: cas-api
    environment: 
      - LocationServicesClient__Username=${LocationServicesClientUsername}
      - LocationServicesClient__Password=${LocationServicesClientPassword}
      - LocationServicesClient__Url=${LocationServicesClientUrl}
      - Keycloak__Client=${KeycloakClient}
      - Keycloak__Authority=${KeycloakAuthority}
      - Keycloak__Secret=${KeycloakSecret}
      - Keycloak__Audience=${KeycloakAudience}
      - DatabaseConnectionString=${DatabaseConnectionString}
      - DataProtectionKeyEncryptionKey=${DataProtectionKeyEncryptionKey}
      - RequestAccessEmailAddress=${RequestAccessEmailAddress}
      - ChesEmailService__ClientId=${ChesEmailServiceClientId}
      - ChesEmailService__Secret=${ChesEmailServiceSecret}
      - ChesEmailService__AuthUrl=${ChesEmailServiceAuthUrl}
      - ChesEmailService__EmailUrl=${ChesEmailServiceEmailUrl}
      - ChesEmailService__SenderEmail=${ChesEmailServiceSenderEmail}
      - ChesEmailService__SenderName=${ChesEmailServiceSenderName}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - WebBaseHref=${WEB_BASE_HREF}
      - SiteMinderLogoutUrl=${SiteMinderLogoutUrl}
      - Logging__LogLevel__Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker=${ControllerLoggingLevel} 
      - Logging__LogLevel__CAS.API.infrastructure.middleware.ErrorHandlingMiddleware=${MiddlewareLoggingLevel} 
      - Logging__LogLevel__Microsoft.EntityFrameworkCore.Database.Command=${DatabaseLoggingLevel}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${KestrelPassword}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${KestrelPath}
      - PdfUrl=${PdfUrl}
      - TrainingNotification=${TrainingNotification}
    ports:
      - 5000:5000
    volumes:
      - ./seed:/opt/app-root/data
    depends_on:
      - db
    command: >
      /bin/bash -c "
        echo Waiting for the database service to start up ...;
        sleep 10;
        /usr/libexec/s2i/run;"

  db:
    #Tried using a redhat image, but it required auth to get it.
    image: centos/postgresql-12-centos7
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_ADMIN_PASSWORD=${POSTGRESQL_ADMIN_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./tmp:/tmp2
  
  pdf:
    image: bcgovimages/weasyprint:63
    ports:
      - 8083:5001